[source.crates-io]
replace-with = "rsproxy-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "sparse+https://rsproxy.cn/index/"

[http]
multiplexing = true

[net]
git-fetch-with-cli = true

[target.x86_64-pc-windows-gnullvm]
linker = "rust-lld"
